export type GuideSlug = "ai-hallucination" | "citation-verification" | "reference-styles";

export interface GuideContent {
    title: string;
    description: string;
    content: string;
    lastUpdated: string;
}

export const guides: Record<GuideSlug, { ja: GuideContent; en: GuideContent }> = {
    "ai-hallucination": {
        ja: {
            title: "AIハルシネーションとは？学術論文における偽引用の問題",
            description: "ChatGPTなどの生成AIが作り出す架空の引用文献「ハルシネーション」について解説。研究者が知っておくべきリスクと対策方法を詳しく説明します。",
            lastUpdated: "2025-01-20",
            content: `
## AIハルシネーションとは

**AIハルシネーション（AI Hallucination）**とは、ChatGPTやClaude、Geminiなどの大規模言語モデル（LLM）が、事実に基づかない情報をあたかも真実であるかのように生成する現象です。学術分野において特に問題となるのが、**存在しない論文や書籍を引用として提示する**ケースです。

## なぜAIは偽の引用を生成するのか

LLMは膨大なテキストデータから学習したパターンに基づいて文章を生成します。学術論文の形式や引用の書き方も学習していますが、**特定の論文が実際に存在するかどうかを検証する機能は持っていません**。

結果として、以下のような問題が発生します：

- **もっともらしい著者名**：実在する研究者の名前を使用
- **信頼できそうなジャーナル名**：実在する学術誌の名称を引用
- **適切な年代**：文脈に合った出版年を生成
- **正しい形式**：APA、MLAなどの引用スタイルに準拠

これらの要素が組み合わさることで、一見して偽物とは判別しにくい「架空の引用」が生成されます。

## 研究への影響

### 学術的信頼性の低下

架空の引用を含む論文は、査読プロセスで発覚した場合、著者の学術的信頼性を大きく損ないます。意図せずとも、**研究不正**と見なされる可能性があります。

### 査読・出版への障壁

多くのジャーナルでは参考文献の正確性を重視しており、存在しない文献の引用は**リジェクトの原因**となります。

### 知識の連鎖の断絶

学術研究は先行研究の積み重ねの上に成り立っています。偽の引用は、**知識の連鎖を断ち切り**、学術コミュニティ全体に悪影響を及ぼします。

## 統計データ

2023年に発表された複数の研究によると：

- ChatGPTが生成した参考文献の**約30%**が架空だったという報告
- 特に専門性の高い分野での引用で誤りが多い傾向
- 最新の研究ほど架空引用の割合が高い

## 対策方法

### 1. 必ず引用を検証する

AIが生成した引用文献は、**必ず手動またはツールで検証**してください。Cite Checkerのようなツールを使えば、Crossref・OpenAlexデータベースとの照合が簡単に行えます。

### 2. DOIの確認

可能な限り**DOI（Digital Object Identifier）**を確認してください。DOIが存在しない、またはリンクが切れている場合は、その引用の信頼性を疑う必要があります。

### 3. 原文へのアクセス

重要な引用については、**必ず原文にアクセス**して内容を確認してください。存在しない論文は当然ながらアクセスできません。

### 4. AIの使い方を見直す

AIを参考文献の「生成」に使用するのではなく、**既存の文献を整理・要約するツール**として活用することを推奨します。

## まとめ

AIハルシネーションは、学術研究において深刻な問題です。生成AIは強力なツールですが、引用文献の検証は研究者自身の責任です。Cite Checkerを活用して、投稿前に必ず参考文献リストの正確性を確認しましょう。
`
        },
        en: {
            title: "What is AI Hallucination? The Problem of Fake Citations in Academic Papers",
            description: "Learn about AI hallucination - fabricated citations generated by AI tools like ChatGPT. Understand the risks for researchers and how to protect your work.",
            lastUpdated: "2025-01-20",
            content: `
## What is AI Hallucination?

**AI Hallucination** refers to the phenomenon where large language models (LLMs) like ChatGPT, Claude, and Gemini generate information that appears factual but is entirely fabricated. In academic contexts, the most concerning manifestation is the **generation of non-existent papers or books as citations**.

## Why Does AI Generate Fake Citations?

LLMs generate text based on patterns learned from vast amounts of training data. While they learn the format of academic papers and citation styles, they **have no mechanism to verify whether a specific paper actually exists**.

This results in problems such as:

- **Plausible author names**: Using names of real researchers
- **Credible journal names**: Citing actual academic journals
- **Appropriate dates**: Generating publication years that fit the context
- **Correct formatting**: Following APA, MLA, and other citation styles

These elements combine to create "fabricated citations" that are difficult to identify at first glance.

## Impact on Research

### Damaged Academic Credibility

Papers containing fake citations can severely damage an author's academic credibility if discovered during peer review. Even unintentional inclusion may be considered **research misconduct**.

### Barriers to Publication

Many journals emphasize reference accuracy, and citations to non-existent works are **grounds for rejection**.

### Breaking the Chain of Knowledge

Academic research builds upon prior work. Fake citations **break this chain of knowledge** and negatively impact the entire scholarly community.

## Statistics

Multiple studies published in 2023 found:

- **Approximately 30%** of ChatGPT-generated references were fabricated
- Errors were more common in highly specialized fields
- More recent references had higher rates of fabrication

## Prevention Strategies

### 1. Always Verify Citations

**Always verify AI-generated citations** manually or with tools. Tools like Cite Checker make it easy to cross-reference against Crossref and OpenAlex databases.

### 2. Check DOIs

Whenever possible, **verify the DOI (Digital Object Identifier)**. If a DOI doesn't exist or links are broken, question that citation's validity.

### 3. Access Original Sources

For important citations, **always access the original text** to verify content. Non-existent papers obviously cannot be accessed.

### 4. Reconsider How You Use AI

Rather than using AI to "generate" references, use it as a **tool for organizing and summarizing existing literature**.

## Conclusion

AI hallucination poses a serious threat to academic research. While generative AI is a powerful tool, verifying citations remains the researcher's responsibility. Use Cite Checker to ensure your reference list is accurate before submission.
`
        }
    },
    "citation-verification": {
        ja: {
            title: "引用検証の重要性：なぜ参考文献を確認すべきなのか",
            description: "学術論文における引用検証の重要性を解説。正確な参考文献リストが研究の信頼性に与える影響と、効率的な検証方法を紹介します。",
            lastUpdated: "2025-01-20",
            content: `
## 引用検証とは

**引用検証**とは、論文の参考文献リストに記載された各引用が、実際に存在し、記述が正確であることを確認するプロセスです。これは学術研究における**基本的な品質管理**の一部です。

## なぜ引用検証が重要なのか

### 1. 研究の信頼性確保

参考文献は、あなたの研究が**既存の知識体系**の上に構築されていることを示す証拠です。不正確な引用は、研究全体の信頼性を損ないます。

### 2. 学術倫理の遵守

多くの学術機関やジャーナルは、参考文献の正確性を**研究倫理の一部**として位置づけています。意図せずとも、誤った引用は問題視される可能性があります。

### 3. 読者への配慮

参考文献を辿って原典にアクセスしようとする読者にとって、**誤記は大きな障壁**となります。正確な引用は学術コミュニティへの貢献です。

### 4. 査読プロセスの円滑化

査読者は参考文献を確認することがあります。正確な引用リストは、**スムーズな査読と出版**につながります。

## よくある引用エラー

### タイポグラフィカルエラー
- 著者名のスペルミス
- 出版年の誤り（例：2021年を2012年と記載）
- ページ番号の転記ミス

### 書誌情報の不完全
- ジャーナル名の省略形の誤り
- 巻号の欠落
- DOIの記載漏れ

### 情報源の混同
- 類似タイトルの論文との取り違え
- 同姓同名の著者の混同
- 版の違い（初版と改訂版など）

## 効率的な検証方法

### 自動検証ツールの活用

Cite Checkerのような自動検証ツールを使用することで、**大量の引用を短時間で検証**できます。Crossref・OpenAlexデータベースとの照合により、実在性と正確性を確認します。

### DOIの活用

DOI（Digital Object Identifier）は論文の**永久的な識別子**です。DOIがある引用は、リンクをクリックするだけで原典にアクセスでき、正確性の確認が容易です。

### 参考文献管理ソフトの利用

Zotero、Mendeley、EndNoteなどの参考文献管理ソフトは、**書誌情報を自動取得**する機能を持っています。手動入力によるエラーを減らすことができます。

## 検証のベストプラクティス

1. **執筆中に随時確認**：完成後にまとめて検証するのではなく、引用を追加するたびに確認
2. **複数のデータベースを使用**：Crossref、OpenAlex、Google Scholarなど複数の情報源で照合
3. **原典にアクセス**：重要な引用は必ず原典を確認
4. **最終チェックの実施**：投稿前に全引用の再検証を行う

## まとめ

引用検証は面倒に感じるかもしれませんが、**研究の品質を保証する重要なステップ**です。自動化ツールを活用して効率化し、正確な参考文献リストを維持しましょう。
`
        },
        en: {
            title: "The Importance of Citation Verification: Why You Should Check Your References",
            description: "Learn why citation verification matters in academic writing. Understand how accurate references impact research credibility and discover efficient verification methods.",
            lastUpdated: "2025-01-20",
            content: `
## What is Citation Verification?

**Citation verification** is the process of confirming that each reference in your bibliography actually exists and is accurately described. This is a fundamental part of **quality control in academic research**.

## Why Citation Verification Matters

### 1. Ensuring Research Credibility

References demonstrate that your research builds upon **existing knowledge**. Inaccurate citations undermine the credibility of your entire work.

### 2. Adhering to Academic Ethics

Many academic institutions and journals consider reference accuracy part of **research ethics**. Even unintentional errors can be problematic.

### 3. Consideration for Readers

For readers trying to access original sources through your references, **errors create significant barriers**. Accurate citations are a contribution to the scholarly community.

### 4. Facilitating Peer Review

Reviewers may check your references. An accurate citation list leads to **smoother review and publication** processes.

## Common Citation Errors

### Typographical Errors
- Misspelled author names
- Wrong publication years (e.g., writing 2012 instead of 2021)
- Transcription errors in page numbers

### Incomplete Bibliographic Information
- Incorrect journal abbreviations
- Missing volume or issue numbers
- Omitted DOIs

### Source Confusion
- Mixing up papers with similar titles
- Confusing authors with the same name
- Wrong editions (first vs. revised)

## Efficient Verification Methods

### Using Automated Verification Tools

Automated tools like Cite Checker allow you to **verify large numbers of citations quickly**. Cross-referencing with Crossref and OpenAlex databases confirms existence and accuracy.

### Leveraging DOIs

DOIs (Digital Object Identifiers) are **permanent identifiers** for papers. Citations with DOIs can be verified simply by clicking the link to access the original source.

### Using Reference Management Software

Reference managers like Zotero, Mendeley, and EndNote can **automatically retrieve bibliographic information**, reducing manual entry errors.

## Best Practices for Verification

1. **Verify as you write**: Check each citation as you add it, rather than waiting until completion
2. **Use multiple databases**: Cross-reference with Crossref, OpenAlex, Google Scholar, and others
3. **Access original sources**: Always verify important citations against the original
4. **Final review**: Re-verify all citations before submission

## Conclusion

Citation verification may seem tedious, but it's a **crucial step in ensuring research quality**. Use automation tools to streamline the process and maintain an accurate reference list.
`
        }
    },
    "reference-styles": {
        ja: {
            title: "引用スタイル完全ガイド：APA、MLA、Chicago、IEEEの違いと使い分け",
            description: "主要な引用スタイル（APA、MLA、Chicago、Harvard、IEEE、Vancouver）の特徴と違いを解説。分野別の推奨スタイルと正しい使い方を学びましょう。",
            lastUpdated: "2025-01-20",
            content: `
## 引用スタイルとは

**引用スタイル**とは、学術論文において参考文献を記載する際の標準化されたフォーマットのことです。著者名、タイトル、出版情報などの要素をどのような順序・形式で記載するかを規定しています。

## 主要な引用スタイル

### APA（American Psychological Association）

**使用分野**：心理学、教育学、社会科学全般

**特徴**：
- 著者-年代システム（例：Smith, 2023）
- 参考文献リストは「References」
- DOIの明記を推奨

**例**：
\`\`\`
Smith, J. A., & Johnson, B. C. (2023). Understanding citation patterns.
Journal of Academic Writing, 15(2), 123-145. https://doi.org/10.1234/jaw.2023.001
\`\`\`

### MLA（Modern Language Association）

**使用分野**：人文学、文学、言語学

**特徴**：
- 著者-ページ番号システム（例：Smith 45）
- 参考文献リストは「Works Cited」
- コンテナ（掲載媒体）の概念を重視

**例**：
\`\`\`
Smith, John A., and Beth C. Johnson. "Understanding Citation Patterns."
Journal of Academic Writing, vol. 15, no. 2, 2023, pp. 123-145.
\`\`\`

### Chicago/Turabian

**使用分野**：歴史学、芸術、一部の社会科学

**特徴**：
- 2つのシステム：脚注/文末注システムと著者-日付システム
- 柔軟性が高く多様な資料タイプに対応
- 参考文献リストは「Bibliography」

**脚注例**：
\`\`\`
1. John A. Smith and Beth C. Johnson, "Understanding Citation Patterns,"
Journal of Academic Writing 15, no. 2 (2023): 125.
\`\`\`

### Harvard

**使用分野**：ビジネス、経済学、一部の自然科学

**特徴**：
- 著者-年代システム（APAに類似）
- 英国・オーストラリアで広く使用
- 各機関で若干の変形あり

**例**：
\`\`\`
Smith, J.A. and Johnson, B.C. (2023) 'Understanding citation patterns',
Journal of Academic Writing, 15(2), pp. 123-145.
\`\`\`

### IEEE

**使用分野**：電気工学、電子工学、コンピュータサイエンス

**特徴**：
- 番号順システム（例：[1], [2]）
- 参考文献は本文中の出現順に番号付け
- 技術論文に最適化

**例**：
\`\`\`
[1] J. A. Smith and B. C. Johnson, "Understanding citation patterns,"
J. Acad. Writing, vol. 15, no. 2, pp. 123-145, 2023.
\`\`\`

### Vancouver

**使用分野**：医学、生物医学、看護学

**特徴**：
- 番号順システム（IEEEに類似）
- 医学ジャーナルで広く採用
- NLM（米国国立医学図書館）スタイルとも呼ばれる

**例**：
\`\`\`
1. Smith JA, Johnson BC. Understanding citation patterns.
J Acad Writing. 2023;15(2):123-145.
\`\`\`

## スタイル選択のポイント

### 1. 投稿先の要件を確認

ジャーナルや学会には**指定されたスタイル**があります。投稿規程を必ず確認してください。

### 2. 分野の慣習に従う

特に指定がない場合は、**その分野で一般的なスタイル**を選択します。

### 3. 一貫性を保つ

一つの文書内では**同一のスタイルを一貫**して使用することが重要です。

## Cite Checkerでの対応

Cite Checkerは、主要な引用スタイル（APA、MLA、Chicago、Harvard、IEEE、Vancouver）を**自動的に検出**します。PDFから抽出された引用は、スタイルに関わらずCrossref・OpenAlexデータベースと照合され、正確性が検証されます。

## まとめ

適切な引用スタイルの選択と正確な適用は、学術論文の**プロフェッショナリズム**を示す重要な要素です。投稿先の要件を確認し、一貫したスタイルで参考文献を記載しましょう。
`
        },
        en: {
            title: "Complete Guide to Citation Styles: APA, MLA, Chicago, IEEE Differences and Usage",
            description: "Comprehensive guide to major citation styles (APA, MLA, Chicago, Harvard, IEEE, Vancouver). Learn their differences, recommended uses by field, and proper formatting.",
            lastUpdated: "2025-01-20",
            content: `
## What are Citation Styles?

**Citation styles** are standardized formats for documenting references in academic papers. They specify the order and format for presenting elements like author names, titles, and publication information.

## Major Citation Styles

### APA (American Psychological Association)

**Fields**: Psychology, Education, Social Sciences

**Characteristics**:
- Author-date system (e.g., Smith, 2023)
- Reference list titled "References"
- DOI inclusion encouraged

**Example**:
\`\`\`
Smith, J. A., & Johnson, B. C. (2023). Understanding citation patterns.
Journal of Academic Writing, 15(2), 123-145. https://doi.org/10.1234/jaw.2023.001
\`\`\`

### MLA (Modern Language Association)

**Fields**: Humanities, Literature, Linguistics

**Characteristics**:
- Author-page number system (e.g., Smith 45)
- Reference list titled "Works Cited"
- Emphasizes container (publication medium) concept

**Example**:
\`\`\`
Smith, John A., and Beth C. Johnson. "Understanding Citation Patterns."
Journal of Academic Writing, vol. 15, no. 2, 2023, pp. 123-145.
\`\`\`

### Chicago/Turabian

**Fields**: History, Arts, Some Social Sciences

**Characteristics**:
- Two systems: Notes-Bibliography and Author-Date
- Highly flexible for diverse source types
- Reference list titled "Bibliography"

**Footnote Example**:
\`\`\`
1. John A. Smith and Beth C. Johnson, "Understanding Citation Patterns,"
Journal of Academic Writing 15, no. 2 (2023): 125.
\`\`\`

### Harvard

**Fields**: Business, Economics, Some Natural Sciences

**Characteristics**:
- Author-date system (similar to APA)
- Widely used in UK and Australia
- Minor variations between institutions

**Example**:
\`\`\`
Smith, J.A. and Johnson, B.C. (2023) 'Understanding citation patterns',
Journal of Academic Writing, 15(2), pp. 123-145.
\`\`\`

### IEEE

**Fields**: Electrical Engineering, Electronics, Computer Science

**Characteristics**:
- Numbered system (e.g., [1], [2])
- References numbered by order of appearance
- Optimized for technical papers

**Example**:
\`\`\`
[1] J. A. Smith and B. C. Johnson, "Understanding citation patterns,"
J. Acad. Writing, vol. 15, no. 2, pp. 123-145, 2023.
\`\`\`

### Vancouver

**Fields**: Medicine, Biomedical Sciences, Nursing

**Characteristics**:
- Numbered system (similar to IEEE)
- Widely adopted by medical journals
- Also called NLM (National Library of Medicine) style

**Example**:
\`\`\`
1. Smith JA, Johnson BC. Understanding citation patterns.
J Acad Writing. 2023;15(2):123-145.
\`\`\`

## Choosing the Right Style

### 1. Check Submission Requirements

Journals and conferences have **specified styles**. Always check the submission guidelines.

### 2. Follow Field Conventions

When not specified, choose the **style common in your field**.

### 3. Maintain Consistency

Using the **same style consistently** throughout a document is essential.

## Cite Checker Support

Cite Checker **automatically detects** major citation styles (APA, MLA, Chicago, Harvard, IEEE, Vancouver). Extracted citations are verified against Crossref and OpenAlex databases regardless of style.

## Conclusion

Selecting and correctly applying the appropriate citation style demonstrates **professionalism** in academic writing. Check your target publication's requirements and maintain consistent reference formatting.
`
        }
    }
};

export const guideList: GuideSlug[] = ["ai-hallucination", "citation-verification", "reference-styles"];
