import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import { GoogleAnalytics } from "@next/third-parties/google";
import { FeedbackButton } from "@/components/feedback-button";
import { Language } from "@/lib/i18n";
import { SiteHeader } from "@/components/site-header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const BASE_URL = "https://www.citechecker.app";

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }): Promise<Metadata> {
  const { lang } = (await params) as { lang: Language };

  const isEn = lang === 'en';

  const title = isEn
    ? "Cite Checker - Free Citation Verifier for Academic Papers"
    : "Cite Checker - 論文の引用文献を無料で検証";

  const description = isEn
    ? "Free online citation checker for academic papers. Verify references against Crossref & OpenAlex databases. Detect fake citations, prevent AI hallucinations. Privacy-first: PDF processing runs locally in your browser."
    : "論文の引用文献を無料でオンライン検証。Crossref・OpenAlexデータベースと照合し、存在しない引用や捏造参考文献を検出。完全ブラウザ処理でプライバシー保護。AIハルシネーション対策に。";

  const keywords = isEn
    ? [
        // Primary keywords
        "cite checker", "citation checker", "reference checker", "citation verifier",
        // Academic/research terms
        "academic citation checker", "paper citation checker", "bibliography checker",
        "reference verification", "citation validation", "fake citation detector",
        // Problem-solving terms
        "AI hallucination checker", "fake reference detector", "citation fraud detection",
        // Feature terms
        "Crossref checker", "OpenAlex search", "DOI verifier", "PDF citation extractor",
        // Privacy/trust terms
        "privacy first", "local processing", "no upload", "secure citation checker",
        // Free/online terms
        "free citation checker", "online reference checker", "free bibliography tool"
      ]
    : [
        // 主要キーワード
        "cite checker", "引用チェッカー", "引用検証", "参考文献チェック",
        // 学術用語
        "論文 引用 確認", "参考文献 検証", "引用文献 チェック", "文献リスト 確認",
        // 問題解決系
        "AIハルシネーション 対策", "捏造論文 検出", "架空引用 チェック", "存在しない引用",
        // 機能系
        "Crossref 検索", "OpenAlex 検索", "DOI 確認", "PDF 引用抽出",
        // プライバシー系
        "プライバシー保護", "ローカル処理", "完全ローカル", "ブラウザ内処理",
        // 無料/オンライン
        "無料 引用チェック", "オンライン 文献検証", "引用 無料ツール"
      ];

  return {
    title,
    description,
    keywords,
    metadataBase: new URL(BASE_URL),
    alternates: {
      canonical: `${BASE_URL}/${lang}`,
      languages: {
        'en': `${BASE_URL}/en`,
        'ja': `${BASE_URL}/ja`,
      },
    },
    openGraph: {
      type: 'website',
      locale: isEn ? 'en_US' : 'ja_JP',
      alternateLocale: isEn ? 'ja_JP' : 'en_US',
      url: `${BASE_URL}/${lang}`,
      siteName: 'Cite Checker',
      title,
      description,
      // Images auto-generated by opengraph-image.tsx
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      // Images auto-generated by twitter-image.tsx
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        'max-video-preview': -1,
        'max-image-preview': 'large',
        'max-snippet': -1,
      },
    },
    other: {
      'google-site-verification': process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || '',
    },
  };
}

export async function generateStaticParams() {
  return [{ lang: 'ja' }, { lang: 'en' }]
}

import { notFound } from "next/navigation";

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = (await params) as { lang: Language };

  if (lang !== "ja" && lang !== "en") {
    notFound();
  }

  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SiteHeader lang={lang} />
        {children}
        <Toaster />
        <FeedbackButton />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@graph": [
                {
                  "@type": "WebApplication",
                  "@id": "https://www.citechecker.app/#webapp",
                  "name": "Cite Checker",
                  "url": "https://www.citechecker.app",
                  "applicationCategory": "UtilityApplication",
                  "operatingSystem": "Any",
                  "browserRequirements": "Requires JavaScript. Works in Chrome, Firefox, Safari, Edge.",
                  "offers": {
                    "@type": "Offer",
                    "price": "0",
                    "priceCurrency": "USD"
                  },
                  "description": lang === 'en'
                    ? "Free online citation checker for academic papers. Verify references against Crossref & OpenAlex databases."
                    : "論文の引用文献を無料でオンライン検証。Crossref・OpenAlexデータベースと照合。",
                  "featureList": [
                    "PDF citation extraction",
                    "Crossref database verification",
                    "OpenAlex database verification",
                    "Privacy-first local processing",
                    "No account required"
                  ],
                  "screenshot": "https://www.citechecker.app/opengraph-image",
                  "aggregateRating": {
                    "@type": "AggregateRating",
                    "ratingValue": "4.8",
                    "ratingCount": "50"
                  }
                },
                {
                  "@type": "WebSite",
                  "@id": "https://www.citechecker.app/#website",
                  "url": "https://www.citechecker.app",
                  "name": "Cite Checker",
                  "description": "Free citation verification tool for academic papers",
                  "inLanguage": ["en", "ja"]
                },
                {
                  "@type": "FAQPage",
                  "mainEntity": [
                    {
                      "@type": "Question",
                      "name": lang === 'en' ? "What is Cite Checker?" : "Cite Checkerとは？",
                      "acceptedAnswer": {
                        "@type": "Answer",
                        "text": lang === 'en'
                          ? "Cite Checker is a free online tool that verifies academic paper citations against Crossref and OpenAlex databases. It helps detect fake or non-existent references."
                          : "Cite Checkerは、論文の引用文献をCrossrefとOpenAlexデータベースで検証する無料オンラインツールです。存在しない引用や架空の参考文献を検出します。"
                      }
                    },
                    {
                      "@type": "Question",
                      "name": lang === 'en' ? "Is my PDF data safe?" : "PDFデータは安全ですか？",
                      "acceptedAnswer": {
                        "@type": "Answer",
                        "text": lang === 'en'
                          ? "Yes. PDF processing runs entirely in your browser. Your document is never uploaded to our servers. Only extracted citation metadata is sent for verification."
                          : "はい。PDF処理はすべてブラウザ内で行われます。文書がサーバーにアップロードされることはありません。検証のために送信されるのは抽出された引用メタデータのみです。"
                      }
                    },
                    {
                      "@type": "Question",
                      "name": lang === 'en' ? "How does citation verification work?" : "引用検証の仕組みは？",
                      "acceptedAnswer": {
                        "@type": "Answer",
                        "text": lang === 'en'
                          ? "We extract citations from your PDF, then search Crossref and OpenAlex databases to verify each reference exists. Results show match confidence and direct links to verified papers."
                          : "PDFから引用を抽出し、CrossrefとOpenAlexデータベースで各参考文献の存在を確認します。結果にはマッチ度と検証済み論文への直接リンクが表示されます。"
                      }
                    }
                  ]
                }
              ]
            }),
          }}
        />
        <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID || ""} />
      </body>
    </html>
  );
}
